---
title: "Untitled"
author: "Keaton Stagaman"
date: "6/7/2017"
output: html_document
runtime: shiny
---


```{r chunk_opts, include=FALSE}
save.width <- 8
save.height <- 6
library(knitr)
opts_chunk$set(echo=FALSE,
               message=FALSE, 
               warning=FALSE, 
               highlight=TRUE,
               fig.height=save.height,
               fig.width=save.width,
               cache=FALSE,
               echo=TRUE)
```

<!-- TO DO:
#   Add in TD/Int Ratio plot (weighted by Attempts)
#   Add in Int/Att plot (weighted by Attempts)
#   Add in Int/Game plot (weighted by Attempts)
-->

```{r libraries-and-data, include=FALSE}
library(RColorBrewer)
library(ggplot2)
theme_set(theme_bw())
library(Hmisc)
library(doBy)
library(gridExtra)
library(reshape2)
source("../Helpful_scripts/mgsub.R")

# Read in all data
all.qbs <- read.table("oregon_qb_stats.txt",
                      sep="\t",
                      header=TRUE,
                      fill=TRUE)

sig.game.shps <- c(16, 1)

# I originally randomly drew colors until I found a set I liked.
# The following makes sure I get those colors again.
set.seed(12)
color.set <- sample(c(brewer.pal(9, "Set1"), brewer.pal(8, "Dark2")), 12)
color.set <- rev(color.set)
brewer.Paired <- brewer.pal(12, "Paired")
color.set[8] <- brewer.Paired[3]
jw <- 0.2

# Determine how many total pass attempts per QB, and
# then remove QBs with less than 100 total pass attempts.
max.cumPassAtt <- summaryBy(cum.pass.atts ~ qb, data=all.qbs, FUN=max)
qbs.sigAtt <- as.character(subset(max.cumPassAtt, cum.pass.atts.max >= 100)$qb)
qbs.sigAtt.data <- droplevels(subset(all.qbs, qb %in% qbs.sigAtt))

# Defining a game with significant attempts at 10.
sig.atts <- 10
qbs.sigAtt.data$sig.game <- factor(ifelse(qbs.sigAtt.data$pass.atts >= sig.atts,
                                   paste("≥", sig.atts, " Pass Atts", sep=""),
                                   paste("<", sig.atts, " Pass Atts", sep="")),
                                   levels=c(paste("≥", sig.atts, " Pass Atts", sep=""),
                                            paste("<", sig.atts, " Pass Atts", sep="")))
qb.cols <- data.frame("qb"=levels(qbs.sigAtt.data$qb), "col"=color.set)
qb.cols$col <- as.character(qb.cols$col)
```

# Career Stats

The first thing I wanted to do was get an idea of what each quarterback had done over the course of their entire career. 

## Cumulative Stats
```{r eruptions, echo=FALSE}
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
)

renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser eruption duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```


```{r cum-yards}
cum.pass.rush.yds <- melt(qbs.sigAtt.data,
                          measure.vars=c("cum.pass.yds", "cum.rush.yds"),
                          variable.name="cum.yds.type",
                          value.name="cum.yds")
cum.pass.rush.yds$cum.yds.type <- factor(mgsub(c("cum.pass.yds", "cum.rush.yds"),
                                               c("Passing", "Rushing"),
                                               cum.pass.rush.yds$cum.yds.type))

inputPanel(
  selectInput("qb_name", label = "Quarterback:",
              choices=levels(cum.pass.rush.yds$qb), selected="Marcus Mariota")
  
  # sliderInput("game_num", label = "Games:",
  #             min = 1, max = max(cum.pass.rush.yds$game.num), value = max(cum.pass.rush.yds$game.num), step = 1)
)

# Plotting cumulative passing and rushing yards over the career of each QB.
renderPlot({
ggplot(data=cum.pass.rush.yds, aes(x=game.num, y=cum.yds, shape=sig.game)) +
    geom_line(aes_string(group=input$qb_name, color=input$qb_name)) +
    geom_point() +
    scale_color_manual(name="QB", values=qb.cols$col) +
    scale_shape_manual(name="Pass Atts/Game", values=sig.game.shps) +
    facet_wrap(~ cum.yds.type, scale="free_y", ncol=1) +
    labs(x="Game #", y="Cumulative Yds")
})
```

<!--
```{r cum-atts-carries}
cum.pass.rush.atts <- melt(qbs.sigAtt.data,
                          measure.vars=c("cum.pass.atts", "cum.comps", "cum.carries"),
                          variable.name="cum.atts.type",
                          value.name="cum.atts")
cum.pass.rush.atts$cum.atts.type <- factor(mgsub(c("cum.pass.atts", "cum.comps", "cum.carries"),
                                               c("Passing Atts", "Passing Comps", "Rushing Atts"),
                                               cum.pass.rush.atts$cum.atts.type),
                                           levels=c("Rushing Atts", "Passing Atts", "Passing Comps"))

# Plotting cumulative passing and rushing attempts over the career of each QB.
ggplot(data=cum.pass.rush.atts, aes(x=game.num, y=cum.atts, color=qb, shape=sig.game)) +
    geom_line(aes(group=qb)) +
    geom_point() +
    scale_color_manual(name="QB", values=qb.cols$col) +
    scale_shape_manual(name="Pass Atts/Game", values=sig.game.shps) +
    facet_wrap(~ cum.atts.type, scale="free_y", ncol=1) +
    labs(x="Game #", y="Cumulative Attempts")
```

```{r cum-tds-ints}
cum.tds.ints <- melt(qbs.sigAtt.data,
                     measure.vars=c("cum.pass.tds", "cum.ints", "cum.rush.tds"),
                     variable.name="cum.result.type",
                     value.name="cum.tds.ints")
cum.tds.ints$cum.result.type <- factor(mgsub(c("cum.pass.tds", "cum.ints", "cum.rush.tds"),
                                             c("Passing TDs", "Interceptions", "Rushing TDs"),
                                             cum.tds.ints$cum.result.type),
                                       levels=c("Rushing TDs", "Passing TDs", "Interceptions"))

# Plotting cumulative TDs (rushing & passing) and interceptions over the career of each QB.
ggplot(data=cum.tds.ints, aes(x=game.num, y=cum.tds.ints, color=qb, shape=sig.game)) +
    geom_line(aes(group=qb)) +
    geom_point() +
    scale_color_manual(name="QB", values=qb.cols$col) +
    scale_shape_manual(name="Pass Atts/Game", values=sig.game.shps) +
    facet_wrap(~ cum.result.type, scale="free_y", ncol=1) +
    labs(x="Game #", y="Cumulative TDs/Ints")
```

## Per Game Stats

```{r pass-rush-yds-game-calc}
pass.yds.data <- qbs.sigAtt.data
wtd.pass.yds <- data.frame(NULL)
for(qb.name in levels(pass.yds.data$qb)) {
    qb.data <- subset(pass.yds.data, qb==qb.name)
    wtd.df <- data.frame("qb"=qb.name,
                         "pass.yds.wtd.mean"=wtd.mean(qb.data$pass.yds,
                                                      weights=qb.data$pass.atts, na.rm=T),
                         "pass.yds.wtd.var"=wtd.var(qb.data$pass.yds,
                                                    weights=qb.data$pass.atts, na.rm=T),
                         "pass.yds.length"=length(qb.data$pass.yds))
    wtd.pass.yds <- rbind(wtd.pass.yds, wtd.df)
}
wtd.pass.yds$pass.yds.wtd.se <- sqrt(wtd.pass.yds$pass.yds.wtd.var/wtd.pass.yds$pass.yds.length)
pass.sort.order <- order(wtd.pass.yds$pass.yds.wtd.mean)
pass.yds.data$qb <- factor(pass.yds.data$qb,
                           levels=levels(wtd.pass.yds$qb)[pass.sort.order])

pass.yds.game <- ggplot(data=pass.yds.data) +
    geom_point(aes(x=qb, y=pass.yds, size=pass.atts, fill=qb),
               shape=21, color="grey", position=position_jitter(width=jw, height=0)) +
    geom_errorbar(data=wtd.pass.yds,
                  aes(ymin=pass.yds.wtd.mean - pass.yds.wtd.se,
                      ymax=pass.yds.wtd.mean + pass.yds.wtd.se,
                      x=qb),
                  size=1) +
    scale_fill_manual(name="QB", values=qb.cols$col[pass.sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Passing Yds/Game", title="Passing Yards per Game (weighted by attempts)") +
    theme(axis.text.x=element_text(angle=30, hjust=1),
          legend.position="bottom")

rush.yds.data <- qbs.sigAtt.data
wtd.rush.yds <- data.frame(NULL)
for(qb.name in levels(rush.yds.data$qb)) {
    qb.data <- subset(rush.yds.data, qb==qb.name)
    wtd.df <- data.frame("qb"=qb.name,
                         "rush.yds.wtd.mean"=wtd.mean(qb.data$rush.yds,
                                                      weights=qb.data$carries, na.rm=T),
                         "rush.yds.wtd.var"=wtd.var(qb.data$rush.yds,
                                                    weights=qb.data$carries, na.rm=T),
                         "rush.yds.length"=length(qb.data$rush.yds))
    wtd.rush.yds <- rbind(wtd.rush.yds, wtd.df)
}
wtd.rush.yds$rush.yds.wtd.se <- sqrt(wtd.rush.yds$rush.yds.wtd.var/wtd.rush.yds$rush.yds.length)
rush.sort.order <- order(wtd.rush.yds$rush.yds.wtd.mean)
rush.yds.data$qb <- factor(rush.yds.data$qb,
                           levels=levels(wtd.rush.yds$qb)[rush.sort.order])

rush.yds.game <- ggplot(data=rush.yds.data) +
    geom_point(aes(x=qb, y=rush.yds, size=carries, fill=qb),
               shape=21, color="grey", position=position_jitter(width=jw, height=0)) +
    geom_errorbar(data=wtd.rush.yds,
                  aes(ymin=rush.yds.wtd.mean - rush.yds.wtd.se,
                      ymax=rush.yds.wtd.mean + rush.yds.wtd.se,
                      x=qb),
                  size=1) +
    scale_fill_manual(name="QB", values=qb.cols$col[rush.sort.order], guide=F) +
    scale_size_continuous(name="Carries/Game") +
    labs(x="QB", y="Rushing Yds/Game", title="Rushing Yards per Game (weighted by carries)") +
    theme(axis.text.x=element_text(angle=30, hjust=1),
          legend.position="bottom")
grid.arrange(pass.yds.game, rush.yds.game, nrow=1)
```

```{r pass-rush-tds-ints-game}
pass.tds.data <- qbs.sigAtt.data
wtd.pass.tds <- data.frame(NULL)
for(qb.name in levels(pass.tds.data$qb)) {
    qb.data <- subset(pass.tds.data, qb==qb.name)
    wtd.df <- data.frame("qb"=qb.name,
                         "pass.tds.wtd.mean"=wtd.mean(qb.data$pass.tds,
                                                      weights=qb.data$pass.atts, na.rm=T),
                         "pass.tds.wtd.var"=wtd.var(qb.data$pass.tds,
                                                    weights=qb.data$pass.atts, na.rm=T),
                         "pass.tds.length"=length(qb.data$pass.tds))
    wtd.pass.tds <- rbind(wtd.pass.tds, wtd.df)
}
wtd.pass.tds$pass.tds.wtd.se <- sqrt(wtd.pass.tds$pass.tds.wtd.var/wtd.pass.tds$pass.tds.length)
pass.sort.order <- order(wtd.pass.tds$pass.tds.wtd.mean)
pass.tds.data$qb <- factor(pass.tds.data$qb,
                           levels=levels(wtd.pass.tds$qb)[pass.sort.order])

pass.tds.game <- ggplot(data=pass.tds.data) +
    geom_point(aes(x=qb, y=pass.tds, size=pass.atts, fill=qb),
               shape=21, color="grey", position=position_jitter(width=jw, height=0)) +
    geom_errorbar(data=wtd.pass.tds,
                  aes(ymin=pass.tds.wtd.mean - pass.tds.wtd.se,
                      ymax=pass.tds.wtd.mean + pass.tds.wtd.se,
                      x=qb),
                  size=1) +
    scale_fill_manual(name="QB", values=qb.cols$col[pass.sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Passing TDs/Game", title="Passing Yards per Game (weighted by attempts)") +
    theme(axis.text.x=element_text(angle=30, hjust=1), 
          legend.position="bottom")

rush.tds.data <- qbs.sigAtt.data
wtd.rush.tds <- data.frame(NULL)
for(qb.name in levels(rush.tds.data$qb)) {
    qb.data <- subset(rush.tds.data, qb==qb.name)
    wtd.df <- data.frame("qb"=qb.name,
                         "rush.tds.wtd.mean"=wtd.mean(qb.data$rush.tds,
                                                      weights=qb.data$carries, na.rm=T),
                         "rush.tds.wtd.var"=wtd.var(qb.data$rush.tds,
                                                    weights=qb.data$carries, na.rm=T),
                         "rush.tds.length"=length(qb.data$rush.tds))
    wtd.rush.tds <- rbind(wtd.rush.tds, wtd.df)
}
wtd.rush.tds$rush.tds.wtd.se <- sqrt(wtd.rush.tds$rush.tds.wtd.var/wtd.rush.tds$rush.tds.length)
rush.sort.order <- order(wtd.rush.tds$rush.tds.wtd.mean)
rush.tds.data$qb <- factor(rush.tds.data$qb,
                           levels=levels(wtd.rush.tds$qb)[rush.sort.order])

rush.tds.game <- ggplot(data=rush.tds.data) +
    geom_point(aes(x=qb, y=rush.tds, size=carries, fill=qb),
               shape=21, color="grey", position=position_jitter(width=jw, height=0)) +
    geom_errorbar(data=wtd.rush.tds,
                  aes(ymin=rush.tds.wtd.mean - rush.tds.wtd.se,
                      ymax=rush.tds.wtd.mean + rush.tds.wtd.se,
                      x=qb),
                  size=1) +
    scale_fill_manual(name="QB", values=qb.cols$col[rush.sort.order], guide=F) +
    scale_size_continuous(name="Carries/Game") +
    labs(x="QB", y="Rushing TDs/Game", title="Passing Yards per Game (weighted by carries)") +
    theme(axis.text.x=element_text(angle=30, hjust=1), 
          legend.position="bottom")

ints.data <- qbs.sigAtt.data
wtd.ints <- data.frame(NULL)
for(qb.name in levels(ints.data$qb)) {
    qb.data <- subset(ints.data, qb==qb.name)
    wtd.df <- data.frame("qb"=qb.name,
                         "ints.wtd.mean"=wtd.mean(qb.data$ints,
                                                      weights=qb.data$pass.atts, na.rm=T),
                         "ints.wtd.var"=wtd.var(qb.data$ints,
                                                    weights=qb.data$pass.atts, na.rm=T),
                         "ints.length"=length(qb.data$ints))
    wtd.ints <- rbind(wtd.ints, wtd.df)
}
wtd.ints$ints.wtd.se <- sqrt(wtd.ints$ints.wtd.var/wtd.ints$ints.length)
ints.sort.order <- order(wtd.ints$ints.wtd.mean)
ints.data$qb <- factor(ints.data$qb,
                           levels=levels(wtd.ints$qb)[ints.sort.order])

ints.game <- ggplot(data=ints.data) +
    geom_point(aes(x=qb, y=ints, size=pass.atts, fill=qb),
               shape=21, color="grey", position=position_jitter(width=jw, height=0)) +
    geom_errorbar(data=wtd.ints,
                  aes(ymin=ints.wtd.mean - ints.wtd.se,
                      ymax=ints.wtd.mean + ints.wtd.se,
                      x=qb),
                  size=1) +
    scale_fill_manual(name="QB", values=qb.cols$col[ints.sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Interceptions/Game", title="Interceptions per Game (weighted by attempts)") +
    theme(axis.text.x=element_text(angle=30, hjust=1), 
          legend.position="bottom")
grid.arrange(pass.tds.game, rush.tds.game, ints.game, nrow=1)
```

```{r comp-pc-game}
comp.pc.data <- qbs.sigAtt.data
comp.pc.data$comp.pc <- comp.pc.data$comps/comp.pc.data$pass.atts
comp.pc.sum <- summaryBy(comp.pc ~ qb, data=comp.pc.data, FUN=mean)
sort.order <- order(comp.pc.sum$comp.pc.mean)
comp.pc.data$qb <- factor(comp.pc.data$qb,
                          levels=levels(comp.pc.sum$qb)[sort.order])
comp.pc.data.p1 <- ggplot(data=comp.pc.data, aes(x=qb, y=comps/pass.atts)) +
    geom_point(aes(size=pass.atts, fill=qb),
               shape=21, color="grey",
               position=position_jitter(width=jw, height=0)) +
    stat_summary(fun.data=mean_se,
                 geom="errorbar",
                 size=1) +
    scale_fill_manual(name="QB", values=qb.cols$col[sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Completion %", title="Unweighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(comp.pc.data.p1,
#        file="~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_uwtd_comp_pc_game.pdf",
#        width=save.width,
#        height=save.height)

comp.pc.data <- qbs.sigAtt.data
wtd.comp.pc <- data.frame(NULL)
for(qb.name in levels(comp.pc.data$qb)) {
    qb.data <- subset(comp.pc.data, qb==qb.name)
    wtd.df <- data.frame("qb"=qb.name,
                         "comp.pc.wtd.mean"=wtd.mean(qb.data$comps/qb.data$pass.atts,
                                                      weights=qb.data$pass.atts, na.rm=T),
                         "comp.pc.wtd.var"=wtd.var(qb.data$comps/qb.data$pass.atts,
                                                    weights=qb.data$pass.atts, na.rm=T),
                         "comp.pc.length"=length(qb.data$comps))
    wtd.comp.pc <- rbind(wtd.comp.pc, wtd.df)
}
wtd.comp.pc$comp.pc.wtd.se <- sqrt(wtd.comp.pc$comp.pc.wtd.var/wtd.comp.pc$comp.pc.length)
sort.order <- order(wtd.comp.pc$comp.pc.wtd.mean)
comp.pc.data$qb <- factor(comp.pc.data$qb,
                             levels=levels(wtd.comp.pc$qb)[sort.order])

comp.pc.data.p2 <- ggplot(data=comp.pc.data) +
    geom_point(aes(x=qb, y=comps/pass.atts, size=pass.atts, fill=qb),
               shape=21, color="grey", position=position_jitter(width=jw, height=0)) +
    geom_errorbar(data=wtd.comp.pc,
                  aes(ymin=comp.pc.wtd.mean - comp.pc.wtd.se,
                      ymax=comp.pc.wtd.mean + comp.pc.wtd.se,
                      x=qb),
                  size=1) +
    scale_fill_manual(name="QB", values=qb.cols$col[sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Completion %", title="Weighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(comp.pc.data.p2,
#        file="~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_wtd_comp_pc_game.pdf",
#        width=save.width,
#        height=save.height)
comp.pc.data.p2
```

## Per Attempt Stats

```{r pass-yds-att}
yds.att.data <- qbs.sigAtt.data
yds.att.data$yds.att <- yds.att.data$pass.yds/yds.att.data$pass.atts
yds.att.sum <- summaryBy(yds.att ~ qb, data=yds.att.data, FUN=mean)
sort.order <- order(yds.att.sum$yds.att.mean)
yds.att.data$qb <- factor(yds.att.data$qb,
                          levels=levels(yds.att.sum$qb)[sort.order])
yds.att.data.p1 <- ggplot(data=yds.att.data, aes(x=qb, y=pass.yds/pass.atts)) +
    geom_point(aes(size=pass.atts, fill=qb),
               shape=21, color="grey",
               position=position_jitter(width=jw, height=0)) +
    stat_summary(fun.data=mean_se,
                 geom="errorbar",
                 size=1) +
    scale_fill_manual(name="QB", values=qb.cols$col[sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Yards/Pass Attempt", title="Unweighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(yds.att.data.p1,
#        file="~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_uwtd_yds_att_game.pdf",
#        width=save.width,
#        height=save.height)

yds.att.data <- qbs.sigAtt.data
wtd.yds.att <- data.frame(NULL)
for(qb.name in levels(yds.att.data$qb)) {
    qb.data <- subset(yds.att.data, qb==qb.name)
    wtd.df <- data.frame("qb"=qb.name,
                         "yds.att.wtd.mean"=wtd.mean(qb.data$pass.yds/qb.data$pass.atts,
                                                     weights=qb.data$pass.atts, na.rm=T),
                         "yds.att.wtd.var"=wtd.var(qb.data$pass.yds/qb.data$pass.atts,
                                                   weights=qb.data$pass.atts, na.rm=T),
                         "yds.att.length"=length(qb.data$pass.yds))
    wtd.yds.att <- rbind(wtd.yds.att, wtd.df)
}
wtd.yds.att$yds.att.wtd.se <- sqrt(wtd.yds.att$yds.att.wtd.var/wtd.yds.att$yds.att.length)
sort.order <- order(wtd.yds.att$yds.att.wtd.mean)
yds.att.data$qb <- factor(yds.att.data$qb,
                          levels=levels(wtd.yds.att$qb)[sort.order])

yds.att.data.p2 <- ggplot(data=yds.att.data) +
    geom_point(aes(x=qb, y=pass.yds/pass.atts, size=pass.atts, fill=qb),
               shape=21, color="grey", position=position_jitter(width=jw, height=0)) +
    geom_errorbar(data=wtd.yds.att,
                  aes(ymin=yds.att.wtd.mean - yds.att.wtd.se,
                      ymax=yds.att.wtd.mean + yds.att.wtd.se,
                      x=qb),
                  size=1) +
    scale_fill_manual(name="QB", values=qb.cols$col[sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Yards/Pass Attempt", title="Weighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(yds.att.data.p2,
#        file="~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_wtd_yds_att_game.pdf",
#        width=save.width,
#        height=save.height)
yds.att.data.p2
```

```{r rush-yds-car}
yds.car.data <- qbs.sigAtt.data
yds.car.data$yds.car <- yds.car.data$rush.yds/yds.car.data$carries
yds.car.sum <- summaryBy(yds.car ~ qb, data=yds.car.data, FUN=mean, na.rm=TRUE)
sort.order <- order(yds.car.sum$yds.car.mean)
yds.car.data$qb <- factor(yds.car.data$qb,
                          levels=levels(yds.car.sum$qb)[sort.order])
yds.car.data.p1 <- ggplot(data=yds.car.data, aes(x=qb, y=rush.yds/carries)) +
    geom_point(aes(size=carries, fill=qb), 
               shape=21, color="grey", position=position_jitter(width=jw, height=0)) +
    stat_summary(fun.data=mean_se,
                 geom="errorbar",
                 size=1) +
    scale_fill_manual(name="QB", values=qb.cols$col[sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Yards/Carry", title="Unweighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(yds.car.data.p1,
#        file="~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_uwtd_yds_car_game.pdf",
#        width=save.width,
#        height=save.height)

yds.car.data <- qbs.sigAtt.data
wtd.yds.car <- data.frame(NULL)
for(qb.name in levels(yds.car.data$qb)) {
    qb.data <- subset(yds.car.data, qb==qb.name)
    wtd.df <- data.frame("qb"=qb.name,
                         "yds.car.wtd.mean"=wtd.mean(qb.data$rush.yds/qb.data$carries,
                                                     weights=qb.data$carries, na.rm=T),
                         "yds.car.wtd.var"=wtd.var(qb.data$rush.yds/qb.data$carries,
                                                   weights=qb.data$carries, na.rm=T),
                         "yds.car.length"=length(qb.data$rush.yds))
    wtd.yds.car <- rbind(wtd.yds.car, wtd.df)
}
wtd.yds.car$yds.car.wtd.se <- sqrt(wtd.yds.car$yds.car.wtd.var/wtd.yds.car$yds.car.length)
sort.order <- order(wtd.yds.car$yds.car.wtd.mean)
yds.car.data$qb <- factor(yds.car.data$qb,
                          levels=levels(wtd.yds.car$qb)[sort.order])

yds.car.data.p2 <- ggplot(data=yds.car.data) +
    geom_point(aes(x=qb, y=rush.yds/carries, size=carries, fill=qb),
               shape=21, color="grey", position=position_jitter(width=jw, height=0)) +
    geom_errorbar(data=wtd.yds.car,
                  aes(ymin=yds.car.wtd.mean - yds.car.wtd.se,
                      ymax=yds.car.wtd.mean + yds.car.wtd.se,
                      x=qb),
                  size=1) +
    scale_fill_manual(name="QB", values=qb.cols$col[sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Yards/Carry", title="Weighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(yds.car.data.p2,
#        file="~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_wtd_yds_car_game.pdf",
#        width=save.width,
#        height=save.height)
yds.car.data.p2
```

# Stats Through First *n* Games

```{r first-n-subsetting}
first.n.maj <- 7
sig.games.data <- droplevels(subset(qbs.sigAtt.data, sig.game==paste("≥", sig.atts, " Pass Atts", sep="")))
sig.games.df <- data.frame(NULL)
for(qb.name in levels(sig.games.data$qb)) {
    qb.sub <- subset(sig.games.data, qb==qb.name)
    game.order <- order(qb.sub$game.num)
    qb.sub <- qb.sub[game.order, ]
    qb.sub$sig.game.num <- c(1:nrow(qb.sub))
    sig.games.df <- rbind(sig.games.df, qb.sub[,c("qb", "game.num", "sig.game.num")])
}
first.n.games <- merge(sig.games.data, sig.games.df, by=c("qb", "game.num"))
first.n.games <- droplevels(subset(first.n.games, sig.game.num <= first.n.maj))
first.n.games$focus <- ifelse(first.n.games$qb=='Justin Herbert', 'yes', 'no')
# levels(first.n.games$qb)
qb.cols.sub <- subset(qb.cols, qb %in% levels(first.n.games$qb))
```

## Cumulative Stats

```{r first-n-cum-yds}
cum.pass.rush.yds <- melt(first.n.games,
                          measure.vars=c("cum.pass.yds", "cum.rush.yds"),
                          variable.name="cum.yds.type",
                          value.name="cum.yds")
cum.pass.rush.yds$cum.yds.type <- factor(mgsub(c("cum.pass.yds", "cum.rush.yds"),
                                               c("Passing", "Rushing"),
                                               cum.pass.rush.yds$cum.yds.type))
cum.pass.rush.yds.p1 <- ggplot(data=cum.pass.rush.yds,
                               aes(x=sig.game.num, y=cum.yds, color=qb, shape=sig.game)) +
    geom_line(aes(group=qb, size=focus)) +
    geom_point() +
    scale_color_manual(name="QB", values=qb.cols.sub$col) +
    scale_shape_manual(name="Pass Atts/Game", values=sig.game.shps) +
    facet_wrap(~ cum.yds.type, ncol=1) +
    scale_x_continuous(breaks=sort(unique(cum.pass.rush.yds$sig.game.num))) +
    labs(x="Significant Game #", y="Cumulative Yds")
# ggsave(cum.pass.rush.yds.p1,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn",
#                   first.n.maj,
#                   "_cum_yds_stat_y.pdf",
#                   sep=""),
#        width=save.width,
#        height=save.height)

cum.pass.rush.yds.p2 <- ggplot(data=cum.pass.rush.yds,
                               aes(x=sig.game.num, y=cum.yds, color=qb, shape=sig.game)) +
    geom_line(aes(group=qb, size=focus)) +
    geom_point() +
    scale_color_manual(name="QB", values=qb.cols.sub$col) +
    scale_shape_manual(name="Pass Atts/Game", values=sig.game.shps, guide=FALSE) +
    scale_size_manual(values=c(0.5, 1.5), guide=FALSE) +
    facet_wrap(~ cum.yds.type, scale="free_y", ncol=1) +
    scale_x_continuous(breaks=sort(unique(cum.pass.rush.yds$sig.game.num))) + 
    labs(x="Significant Game #", y="Cumulative Yds")
# ggsave(cum.pass.rush.yds.p2, file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", first.n.maj, "_cum_yds_free_y.pdf", sep=""),
#        width=save.width,
#        height=save.height)
cum.pass.rush.yds.p2
```

```{r first-n-cum-atts}
cum.pass.rush.atts <- melt(first.n.games,
                           measure.vars=c("cum.pass.atts", "cum.comps", "cum.carries"),
                           variable.name="cum.atts.type",
                           value.name="cum.atts")
cum.pass.rush.atts$cum.atts.type <- factor(mgsub(c("cum.pass.atts", "cum.comps", "cum.carries"),
                                                 c("Passing Atts", "Passing Comps", "Rushing Atts"),
                                                 cum.pass.rush.atts$cum.atts.type),
                                           levels=c("Rushing Atts", "Passing Atts", "Passing Comps"))

cum.pass.rush.atts.p1 <- ggplot(data=cum.pass.rush.atts,
                                aes(x=sig.game.num, y=cum.atts, color=qb, shape=sig.game)) +
    geom_line(aes(group=qb, size=focus)) +
    geom_point() +
    scale_color_manual(name="QB", values=qb.cols.sub$col) +
    scale_shape_manual(name="Pass Atts/Game", values=sig.game.shps) +
    scale_size_manual(values=c(0.5, 1.5), guide=FALSE) +
    facet_wrap(~ cum.atts.type, ncol=1) +
    labs(x="Game #", y="Cumulative Attempts or Completions")
# ggsave(cum.pass.rush.atts.p1,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", 
#                   first.n.maj, 
#                   "_cum_atts_stat_y.pdf", 
#                   sep=""),
#        width=save.width,
#        height=save.height)

cum.pass.rush.atts.p2 <- ggplot(data=cum.pass.rush.atts,
                                aes(x=sig.game.num, y=cum.atts, color=qb, shape=sig.game)) +
    geom_line(aes(group=qb, size=focus)) +
    geom_point() +
    scale_color_manual(name="QB", values=qb.cols.sub$col) +
    scale_shape_manual(name="Pass Atts/Game", values=sig.game.shps) +
    scale_size_manual(values=c(0.5, 1.5), guide=FALSE) +
    facet_wrap(~ cum.atts.type, scale="free_y", ncol=1) +
    labs(x="Game #", y="Cumulative Attempts")
# ggsave(cum.pass.rush.atts.p2,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", 
#                   first.n.maj, 
#                   "_cum_atts_free_y.pdf", 
#                   sep=""),
#        width=save.width,
#        height=save.height)
cum.pass.rush.atts.p2
```

```{r first-n-cum-tds-ints}
cum.tds.ints <- melt(first.n.games,
                     measure.vars=c("cum.pass.tds", "cum.ints", "cum.rush.tds"),
                     variable.name="cum.result.type",
                     value.name="cum.tds.ints")
cum.tds.ints$cum.result.type <- factor(mgsub(c("cum.pass.tds", "cum.ints", "cum.rush.tds"),
                                             c("Passing TDs", "Interceptions", "Rushing TDs"),
                                             cum.tds.ints$cum.result.type),
                                       levels=c("Rushing TDs", "Passing TDs", "Interceptions"))
cum.tds.ints.p1 <- ggplot(data=cum.tds.ints, aes(x=sig.game.num, y=cum.tds.ints, color=qb, shape=sig.game)) +
    geom_line(aes(group=qb, size=focus)) +
    geom_point() +
    scale_color_manual(name="QB", values=qb.cols.sub$col) +
    scale_shape_manual(name="Pass Atts/Game", values=sig.game.shps) +
    scale_size_manual(values=c(0.5, 1.5), guide=FALSE) +
    facet_wrap(~ cum.result.type, ncol=1) +
    labs(x="Game #", y="Cumulative TDs/Ints")
# ggsave(cum.tds.ints.p1,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", 
#                   first.n.maj, 
#                   "_cum_tds_ints_stat_y.pdf", 
#                   sep=""),
#        width=save.width,
#        height=save.height)

cum.tds.ints.p2 <- ggplot(data=cum.tds.ints, aes(x=sig.game.num, y=cum.tds.ints, color=qb, shape=sig.game)) +
    geom_line(aes(group=qb, size=focus)) +
    geom_point() +
    scale_color_manual(name="QB", values=qb.cols.sub$col) +
    scale_shape_manual(name="Pass Atts/Game", values=sig.game.shps) +
    scale_size_manual(values=c(0.5, 1.5), guide=FALSE) +
    facet_wrap(~ cum.result.type, scale="free_y", ncol=1) +
    labs(x="Game #", y="Cumulative TDs/Ints")
# ggsave(cum.tds.ints.p2,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", 
#                   first.n.maj, 
#                   "_cum_tds_ints_free_y.pdf", 
#                   sep=""),
#        width=save.width,
#        height=save.height)
cum.tds.ints.p2
```

## Per Game Stats

```{r first-n-pass-yds-game}
pass.yds.data <- first.n.games
pass.yds.sum <- summaryBy(pass.yds ~ qb, data=pass.yds.data, FUN=mean)
sort.order <- order(pass.yds.sum$pass.yds.mean)
pass.yds.data$qb <- factor(pass.yds.data$qb,
                           levels=levels(pass.yds.sum$qb)[sort.order])
pass.yds.data.p1 <- ggplot(data=pass.yds.data, aes(x=qb, y=pass.yds)) +
    geom_point(aes(size=pass.atts, fill=qb),
               shape=21, color="grey",
               position=position_jitter(width=jw, height=0)) +
    stat_summary(fun.data=mean_se,
                 geom="errorbar",
                 size=1) +
    scale_fill_manual(name="QB", values=qb.cols.sub$col[sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Passing Yds/Game", title="Unweighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(pass.yds.data.p1,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", 
#                   first.n.maj, 
#                   "_uwtd_pass_yds_game.pdf", 
#                   sep=""),
#        width=save.width,
#        height=save.height)

pass.yds.data <- first.n.games
wtd.pass.yds <- data.frame(NULL)
for(qb.name in levels(pass.yds.data$qb)) {
    qb.data <- subset(pass.yds.data, qb==qb.name)
    wtd.df <- data.frame("qb"=qb.name,
                         "pass.yds.wtd.mean"=wtd.mean(qb.data$pass.yds,
                                                      weights=qb.data$pass.atts, na.rm=T),
                         "pass.yds.wtd.var"=wtd.var(qb.data$pass.yds,
                                                    weights=qb.data$pass.atts, na.rm=T),
                         "pass.yds.length"=length(qb.data$pass.yds))
    wtd.pass.yds <- rbind(wtd.pass.yds, wtd.df)
}
wtd.pass.yds$pass.yds.wtd.se <- sqrt(wtd.pass.yds$pass.yds.wtd.var/wtd.pass.yds$pass.yds.length)
sort.order <- order(wtd.pass.yds$pass.yds.wtd.mean)
pass.yds.data$qb <- factor(pass.yds.data$qb,
                           levels=levels(wtd.pass.yds$qb)[sort.order])

pass.yds.data.p2 <- ggplot(data=pass.yds.data) +
    geom_point(aes(x=qb, y=pass.yds, size=pass.atts, fill=qb),
               shape=21, color="grey", position=position_jitter(width=jw, height=0)) +
    geom_errorbar(data=wtd.pass.yds,
                  aes(ymin=pass.yds.wtd.mean - pass.yds.wtd.se,
                      ymax=pass.yds.wtd.mean + pass.yds.wtd.se,
                      x=qb),
                  size=1) +
    scale_fill_manual(name="QB", values=qb.cols.sub$col[sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Passing Yds/Game", title="Weighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(pass.yds.data.p2,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", 
#                   first.n.maj, 
#                   "_wtd_pass_yds_game.pdf", 
#                   sep=""),
#        width=save.width,
#        height=save.height)
pass.yds.data.p2
```

```{r first-n-rush-yds-game}
rush.yds.data <- first.n.games
rush.yds.sum <- summaryBy(rush.yds ~ qb, data=rush.yds.data, FUN=mean)
sort.order <- order(rush.yds.sum$rush.yds.mean)
rush.yds.data$qb <- factor(rush.yds.data$qb,
                           levels=levels(rush.yds.sum$qb)[sort.order])
rush.yds.data.p1 <- ggplot(data=rush.yds.data, aes(x=qb, y=rush.yds)) +
    geom_point(aes(size=carries, fill=qb),
               shape=21, color="grey",
               position=position_jitter(width=jw, height=0)) +
    stat_summary(fun.data=mean_se,
                 geom="errorbar",
                 size=1) +
    scale_fill_manual(name="QB", values=qb.cols.sub$col[sort.order], guide=F) +
    scale_size_continuous(name="Carries/Game") +
    labs(x="QB", y="Rushing Yds/Game", title="Unweighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(rush.yds.data.p1,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", 
#                   first.n.maj, 
#                   "_uwtd_rush_yds_game.pdf", 
#                   sep=""),
#        width=save.width,
#        height=save.height)

rush.yds.data <- first.n.games
wtd.rush.yds <- data.frame(NULL)
for(qb.name in levels(rush.yds.data$qb)) {
    qb.data <- subset(rush.yds.data, qb==qb.name)
    wtd.df <- data.frame("qb"=qb.name,
                         "rush.yds.wtd.mean"=wtd.mean(qb.data$rush.yds,
                                                      weights=qb.data$carries, na.rm=T),
                         "rush.yds.wtd.var"=wtd.var(qb.data$rush.yds,
                                                    weights=qb.data$carries, na.rm=T),
                         "rush.yds.length"=length(qb.data$rush.yds))
    wtd.rush.yds <- rbind(wtd.rush.yds, wtd.df)
}
wtd.rush.yds$rush.yds.wtd.se <- sqrt(wtd.rush.yds$rush.yds.wtd.var/wtd.rush.yds$rush.yds.length)
sort.order <- order(wtd.rush.yds$rush.yds.wtd.mean)
rush.yds.data$qb <- factor(rush.yds.data$qb,
                           levels=levels(wtd.rush.yds$qb)[sort.order])

rush.yds.data.p2 <- ggplot(data=rush.yds.data) +
    geom_point(aes(x=qb, y=rush.yds, size=carries, fill=qb),
               shape=21, color="grey", position=position_jitter(width=jw, height=0)) +
    geom_errorbar(data=wtd.rush.yds,
                  aes(ymin=rush.yds.wtd.mean - rush.yds.wtd.se,
                      ymax=rush.yds.wtd.mean + rush.yds.wtd.se,
                      x=qb),
                  size=1) +
    scale_fill_manual(name="QB", values=qb.cols.sub$col[sort.order], guide=F) +
    scale_size_continuous(name="Carries/Game") +
    labs(x="QB", y="Rushing Yds/Game", title="Weighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(rush.yds.data.p2,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", 
#                   first.n.maj, 
#                   "_wtd_rush_yds_game.pdf", 
#                   sep=""),
#        width=save.width,
#        height=save.height)
rush.yds.data.p2
```

```{r first-n-pass-tds-game}
pass.tds.data <- first.n.games
pass.tds.sum <- summaryBy(pass.tds ~ qb, data=pass.tds.data, FUN=mean)
sort.order <- order(pass.tds.sum$pass.tds.mean)
pass.tds.data$qb <- factor(pass.tds.data$qb,
                           levels=levels(pass.tds.sum$qb)[sort.order])
pass.tds.data.p1 <- ggplot(data=pass.tds.data, aes(x=qb, y=pass.tds)) +
    geom_point(aes(size=pass.atts, fill=qb),
               shape=21, color="grey",
               position=position_jitter(width=jw, height=0)) +
    stat_summary(fun.data=mean_se,
                 geom="errorbar",
                 size=1) +
    scale_fill_manual(name="QB", values=qb.cols.sub$col[sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Passing TDs/Game", title="Unweighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(pass.tds.data.p1,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", 
#                   first.n.maj, 
#                   "_uwtd_pass_tds_game.pdf", 
#                   sep=""),
#        width=save.width,
#        height=save.height)

pass.tds.data <- first.n.games
wtd.pass.tds <- data.frame(NULL)
for(qb.name in levels(pass.tds.data$qb)) {
    qb.data <- subset(pass.tds.data, qb==qb.name)
    wtd.df <- data.frame("qb"=qb.name,
                         "pass.tds.wtd.mean"=wtd.mean(qb.data$pass.tds,
                                                      weights=qb.data$pass.atts, na.rm=T),
                         "pass.tds.wtd.var"=wtd.var(qb.data$pass.tds,
                                                    weights=qb.data$pass.atts, na.rm=T),
                         "pass.tds.length"=length(qb.data$pass.tds))
    wtd.pass.tds <- rbind(wtd.pass.tds, wtd.df)
}
wtd.pass.tds$pass.tds.wtd.se <- sqrt(wtd.pass.tds$pass.tds.wtd.var/wtd.pass.tds$pass.tds.length)
sort.order <- order(wtd.pass.tds$pass.tds.wtd.mean)
pass.tds.data$qb <- factor(pass.tds.data$qb,
                           levels=levels(wtd.pass.tds$qb)[sort.order])

pass.tds.data.p2 <- ggplot(data=pass.tds.data) +
    geom_point(aes(x=qb, y=pass.tds, size=pass.atts, fill=qb),
               shape=21, color="grey", position=position_jitter(width=jw, height=0)) +
    geom_errorbar(data=wtd.pass.tds,
                  aes(ymin=pass.tds.wtd.mean - pass.tds.wtd.se,
                      ymax=pass.tds.wtd.mean + pass.tds.wtd.se,
                      x=qb),
                  size=1) +
    scale_fill_manual(name="QB", values=qb.cols.sub$col[sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Passing TDs/Game", title="Weighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(pass.tds.data.p2,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", 
#                   first.n.maj, 
#                   "_wtd_pass_tds_game.pdf", 
#                   sep=""),
#        width=save.width,
#        height=save.height)
pass.tds.data.p2
```

```{r first-n-rush-tds-game}
rush.tds.data <- first.n.games
rush.tds.sum <- summaryBy(rush.tds ~ qb, data=rush.tds.data, FUN=mean)
sort.order <- order(rush.tds.sum$rush.tds.mean)
rush.tds.data$qb <- factor(rush.tds.data$qb,
                           levels=levels(rush.tds.sum$qb)[sort.order])
rush.tds.data.p1 <- ggplot(data=rush.tds.data, aes(x=qb, y=as.numeric(rush.tds))) +
    geom_point(aes(size=carries, fill=qb),
               shape=21, color="grey",
               position=position_jitter(width=jw, height=0)) +
    stat_summary(fun.data=mean_se,
                 geom="errorbar",
                 size=1) +
    scale_fill_manual(name="QB", values=qb.cols.sub$col[sort.order], guide=F) +
    scale_size_continuous(name="Carries/Game") +
    labs(x="QB", y="Rushing TDs/Game", title="Unweighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(rush.tds.data.p1,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", 
#                   first.n.maj, 
#                   "_uwtd_rush_tds_game.pdf", 
#                   sep=""),
#        width=save.width,
#        height=save.height)

rush.tds.data <- first.n.games
wtd.rush.tds <- data.frame(NULL)
for(qb.name in levels(rush.tds.data$qb)) {
    qb.data <- subset(rush.tds.data, qb==qb.name)
    wtd.df <- data.frame("qb"=qb.name,
                         "rush.tds.wtd.mean"=wtd.mean(qb.data$rush.tds,
                                                      weights=qb.data$carries, na.rm=T),
                         "rush.tds.wtd.var"=wtd.var(qb.data$rush.tds,
                                                    weights=qb.data$carries, na.rm=T),
                         "rush.tds.length"=length(qb.data$rush.tds))
    wtd.rush.tds <- rbind(wtd.rush.tds, wtd.df)
}
wtd.rush.tds$rush.tds.wtd.se <- sqrt(wtd.rush.tds$rush.tds.wtd.var/wtd.rush.tds$rush.tds.length)
sort.order <- order(wtd.rush.tds$rush.tds.wtd.mean)
rush.tds.data$qb <- factor(rush.tds.data$qb,
                           levels=levels(wtd.rush.tds$qb)[sort.order])

rush.tds.data.p2 <- ggplot(data=rush.tds.data) +
    geom_point(aes(x=qb, y=rush.tds, size=carries, fill=qb),
               shape=21, color="grey", position=position_jitter(width=jw, height=0)) +
    geom_errorbar(data=wtd.rush.tds,
                  aes(ymin=rush.tds.wtd.mean - rush.tds.wtd.se,
                      ymax=rush.tds.wtd.mean + rush.tds.wtd.se,
                      x=qb),
                  size=1) +
    scale_fill_manual(name="QB", values=qb.cols.sub$col[sort.order], guide=F) +
    scale_size_continuous(name="Carries/Game") +
    labs(x="QB", y="Rushing TDs/Game", title="Weighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(rush.tds.data.p2,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", 
#                   first.n.maj, 
#                   "_wtd_rush_tds_game.pdf", 
#                   sep=""),
#        width=save.width,
#        height=save.height)
rush.tds.data.p2
```

```{r first-n-comp-pc-game}
comp.pc.data <- first.n.games
comp.pc.data$comp.pc <- comp.pc.data$comps/comp.pc.data$pass.atts
comp.pc.sum <- summaryBy(comp.pc ~ qb, data=comp.pc.data, FUN=mean)
sort.order <- order(comp.pc.sum$comp.pc.mean)
comp.pc.data$qb <- factor(comp.pc.data$qb,
                          levels=levels(comp.pc.sum$qb)[sort.order])
comp.pc.data.p1 <- ggplot(data=comp.pc.data, aes(x=qb, y=comps/pass.atts)) +
    geom_point(aes(size=pass.atts, fill=qb),
               shape=21, color="grey",
               position=position_jitter(width=jw, height=0)) +
    stat_summary(fun.data=mean_se,
                 geom="errorbar",
                 size=1) +
    scale_fill_manual(name="QB", values=qb.cols.sub$col[sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Completion %", title="Unweighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(comp.pc.data.p1,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", 
#                   first.n.maj, 
#                   "_uwtd_comp_pc_game.pdf", 
#                   sep=""),
#        width=save.width,
#        height=save.height)

comp.pc.data <- first.n.games
wtd.comp.pc <- data.frame(NULL)
for(qb.name in levels(comp.pc.data$qb)) {
    qb.data <- subset(comp.pc.data, qb==qb.name)
    wtd.df <- data.frame("qb"=qb.name,
                         "comp.pc.wtd.mean"=wtd.mean(qb.data$comps/qb.data$pass.atts,
                                                     weights=qb.data$pass.atts, na.rm=T),
                         "comp.pc.wtd.var"=wtd.var(qb.data$comps/qb.data$pass.atts,
                                                   weights=qb.data$pass.atts, na.rm=T),
                         "comp.pc.length"=length(qb.data$comps))
    wtd.comp.pc <- rbind(wtd.comp.pc, wtd.df)
}
wtd.comp.pc$comp.pc.wtd.se <- sqrt(wtd.comp.pc$comp.pc.wtd.var/wtd.comp.pc$comp.pc.length)
sort.order <- order(wtd.comp.pc$comp.pc.wtd.mean)
comp.pc.data$qb <- factor(comp.pc.data$qb,
                          levels=levels(wtd.comp.pc$qb)[sort.order])

comp.pc.data.p2 <- ggplot(data=comp.pc.data) +
    geom_point(aes(x=qb, y=comps/pass.atts, size=pass.atts, fill=qb),
               shape=21, color="grey", position=position_jitter(width=jw, height=0)) +
    geom_errorbar(data=wtd.comp.pc,
                  aes(ymin=comp.pc.wtd.mean - comp.pc.wtd.se,
                      ymax=comp.pc.wtd.mean + comp.pc.wtd.se,
                      x=qb),
                  size=1) +
    scale_fill_manual(name="QB", values=qb.cols.sub$col[sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Completion %", title="Weighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(comp.pc.data.p2,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", 
#                   first.n.maj, 
#                   "_wtd_comp_pc_game.pdf", 
#                   sep=""),
#        width=save.width,
#        height=save.height)
comp.pc.data.p2
```

## Per Attempt Stats

```{r first-n-pass-yds-att}
yds.att.data <- first.n.games
yds.att.data$yds.att <- yds.att.data$pass.yds/yds.att.data$pass.atts
yds.att.sum <- summaryBy(yds.att ~ qb, data=yds.att.data, FUN=mean)
sort.order <- order(yds.att.sum$yds.att.mean)
yds.att.data$qb <- factor(yds.att.data$qb,
                          levels=levels(yds.att.sum$qb)[sort.order])
yds.att.data.p1 <- ggplot(data=yds.att.data, aes(x=qb, y=pass.yds/pass.atts)) +
    geom_point(aes(size=pass.atts, fill=qb),
               shape=21, color="grey",
               position=position_jitter(width=jw, height=0)) +
    stat_summary(fun.data=mean_se,
                 geom="errorbar",
                 size=1) +
    scale_fill_manual(name="QB", values=qb.cols.sub$col[sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Yards/Pass Attempt", title="Unweighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(yds.att.data.p1,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", 
#                   first.n.maj, 
#                   "_uwtd_yds_att_game.pdf", 
#                   sep=""),
#        width=save.width,
#        height=save.height)

yds.att.data <- first.n.games
wtd.yds.att <- data.frame(NULL)
for(qb.name in levels(yds.att.data$qb)) {
    qb.data <- subset(yds.att.data, qb==qb.name)
    wtd.df <- data.frame("qb"=qb.name,
                         "yds.att.wtd.mean"=wtd.mean(qb.data$pass.yds/qb.data$pass.atts,
                                                     weights=qb.data$pass.atts, na.rm=T),
                         "yds.att.wtd.var"=wtd.var(qb.data$pass.yds/qb.data$pass.atts,
                                                   weights=qb.data$pass.atts, na.rm=T),
                         "yds.att.length"=length(qb.data$pass.yds))
    wtd.yds.att <- rbind(wtd.yds.att, wtd.df)
}
wtd.yds.att$yds.att.wtd.se <- sqrt(wtd.yds.att$yds.att.wtd.var/wtd.yds.att$yds.att.length)
sort.order <- order(wtd.yds.att$yds.att.wtd.mean)
yds.att.data$qb <- factor(yds.att.data$qb,
                          levels=levels(wtd.yds.att$qb)[sort.order])

yds.att.data.p2 <- ggplot(data=yds.att.data) +
    geom_point(aes(x=qb, y=pass.yds/pass.atts, size=pass.atts, fill=qb),
               shape=21, color="grey", position=position_jitter(width=jw, height=0)) +
    geom_errorbar(data=wtd.yds.att,
                  aes(ymin=yds.att.wtd.mean - yds.att.wtd.se,
                      ymax=yds.att.wtd.mean + yds.att.wtd.se,
                      x=qb),
                  size=1) +
    scale_fill_manual(name="QB", values=qb.cols.sub$col[sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Yards/Pass Attempt", title="Weighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(yds.att.data.p2,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", 
#                   first.n.maj, 
#                   "_wtd_yds_att_game.pdf", 
#                   sep=""),
#        width=save.width,
#        height=save.height)
yds.att.data.p2
```

```{r first-n-rush-yds-car}
yds.car.data <- first.n.games
yds.car.data$yds.car <- yds.car.data$rush.yds/yds.car.data$carries
yds.car.sum <- summaryBy(yds.car ~ qb, data=yds.car.data, FUN=mean, na.rm=TRUE)
sort.order <- order(yds.car.sum$yds.car.mean)
yds.car.data$qb <- factor(yds.car.data$qb,
                          levels=levels(yds.car.sum$qb)[sort.order])
yds.car.data.p1 <- ggplot(data=yds.car.data, aes(x=qb, y=rush.yds/carries)) +
    geom_point(aes(size=carries, fill=qb), shape=21, color="grey", position=position_jitter(width=jw, height=0)) +
    stat_summary(fun.data=mean_se,
                 geom="errorbar",
                 size=1) +
    scale_fill_manual(name="QB", values=qb.cols.sub$col[sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Yards/Carry", title="Unweighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(yds.car.data.p1,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", 
#                   first.n.maj, 
#                   "_uwtd_yds_car_game.pdf", 
#                   sep=""),
#        width=save.width,
#        height=save.height)

yds.car.data <- first.n.games
wtd.yds.car <- data.frame(NULL)
for(qb.name in levels(yds.car.data$qb)) {
    qb.data <- subset(yds.car.data, qb==qb.name)
    wtd.df <- data.frame("qb"=qb.name,
                         "yds.car.wtd.mean"=wtd.mean(qb.data$rush.yds/qb.data$carries,
                                                     weights=qb.data$carries, na.rm=T),
                         "yds.car.wtd.var"=wtd.var(qb.data$rush.yds/qb.data$carries,
                                                   weights=qb.data$carries, na.rm=T),
                         "yds.car.length"=length(qb.data$rush.yds))
    wtd.yds.car <- rbind(wtd.yds.car, wtd.df)
}
wtd.yds.car$yds.car.wtd.se <- sqrt(wtd.yds.car$yds.car.wtd.var/wtd.yds.car$yds.car.length)
sort.order <- order(wtd.yds.car$yds.car.wtd.mean)
yds.car.data$qb <- factor(yds.car.data$qb,
                          levels=levels(wtd.yds.car$qb)[sort.order])

yds.car.data.p2 <- ggplot(data=yds.car.data) +
    geom_point(aes(x=qb, y=rush.yds/carries, size=carries, fill=qb),
               shape=21, color="grey", position=position_jitter(width=jw, height=0)) +
    geom_errorbar(data=wtd.yds.car,
                  aes(ymin=yds.car.wtd.mean - yds.car.wtd.se,
                      ymax=yds.car.wtd.mean + yds.car.wtd.se,
                      x=qb),
                  size=1) +
    scale_fill_manual(name="QB", values=qb.cols.sub$col[sort.order], guide=F) +
    scale_size_continuous(name="Attempts/Game") +
    labs(x="QB", y="Yards/Carry", title="Weighted") +
    theme(axis.text.x=element_text(angle=30, hjust=1))
# ggsave(yds.car.data.p2,
#        file=paste("~/Documents/CFB poll prediction/UO_stats/oregon_qb_stats_fn", 
#                   first.n.maj, 
#                   "_wtd_yds_car_game.pdf", 
#                   sep=""),
#        width=save.width,
#        height=save.height)
yds.car.data.p2
```
